env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
plugins:
  - '@typescript-eslint'
rules: {}
