name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main # Set a branch name to trigger deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Run Lint
        run: |
          npm ci
          npm run lint
